export const samplefood=[
    {
        id:'1',
        name:'Poisson',
        cooktime:'10-20',
        price:4,
        favorite:true,
        origins:['tunisie'],
        stars:4.5,
        imgUrl:'hout.png',
        tags:['FastFood','Supplement']
    },
    {
        id:'2',
        name:'Scalope',
        cooktime:'10-20',
        price:3,
        favorite:false,
        origins:['tunisie'],
        stars:4.7,
        imgUrl:'scalope.png',
        tags:['FastFood','Supplement']
    },
    {
        id:'3',
        name:'Merguez',
        cooktime:'10-20',
        price:3,
        favorite:false,
        origins:['tunisie'],
        stars:4.3,
        imgUrl:'merguez.png',
        tags:['FastFood','Supplement']
    },
    {
        id:'4',
        name:'Tastira',
        cooktime:'20-30',
        price:3,
        favorite:true,
        origins:['tunisie'],
        stars:4.3,
        imgUrl:'tastira.png',
        tags:['FastFood','Lunch']
    },
    {
        id:'5',
        name:'Makarouna',
        cooktime:'30-40',
        price:8,
        favorite:false,
        origins:['italy'],
        stars:4.5,
        imgUrl:'makarouna.png',
        tags:['SlowFood','Lunch']
    },
    {
        id:'6',
        name:'Plat Tunisian',
        cooktime:'10-20',
        price:4.5,
        favorite:false,
        origins:['tunisie'],
        stars:4.5,
        imgUrl:'shantn.png',
        tags:['FastFood']
    },
    {
        id:'7',
        name:'Salade',
        cooktime:'10-20',
        price:3,
        favorite:true,
        origins:['tunisie'],
        stars:4.5,
        imgUrl:'slata.png',
        tags:['FastFood','Supplement']
    },
    {
        id:'8',
        name:'Kaftagi',
        cooktime:'10-20',
        price:5,
        favorite:false,
        origins:['tunisie'],
        stars:4.5,
        imgUrl:'kaftagi.png',
        tags:['FastFood','Lunch']
    },
    {
        id:'9',
        name:'Sandwich',
        cooktime:'10-20',
        price:3.5,
        favorite:false,
        origins:['tunisie'],
        stars:4.5,
        imgUrl:'tabouna.png',
        tags:['FastFood','Lunch']
    },
    {
        id:'10',
        name:'Chapati',
        cooktime:'10-20',
        price:3,
        favorite:false,
        origins:['tunisie'],
        stars:4.5,
        imgUrl:'chapati.png',
        tags:['FastFood','Lunch']
    },
    {
        id:'11',
        name:'Pizza',
        cooktime:'10-20',
        price:7,
        favorite:false,
        origins:['italy'],
        stars:4.6,
        imgUrl:'pizzza.png',
        tags:['FastFood','Pizza']
    },
    {
        id:'12',
        name:'Brikk',
        cooktime:'15-20',
        price:2,
        favorite:true,
        origins:['tunise'],
        stars:4.8,
        imgUrl:'brikk.png',
        tags:['FastFood','Supplement']
    },
    {
        id:'13',
        name:'Tajin',
        cooktime:'15-20',
        price:2,
        favorite:true,
        origins:['italy'],
        stars:4.8,
        imgUrl:'tajin.png',
        tags:['Supplement']
    },
    {
        id:'14',
        name:'Libanaise',
        cooktime:'15-20',
        price:2,
        favorite:true,
        origins:['italy'],
        stars:4.8,
        imgUrl:'libanaise.png',
        tags:['Gateau']
    },
    {
        id:'15',
        name:'Millfeuille',
        cooktime:'15-20',
        price:2,
        favorite:true,
        origins:['tunisie'],
        stars:4.8,
        imgUrl:'milfeuil.png',
        tags:['Gateau']
    },
    {
        id:'16',
        name:'Gateau Pyramide',
        cooktime:'15-20',
        price:2,
        favorite:true,
        origins:['italy'],
        stars:4.8,
        imgUrl:'gateaupyramide.png',
        tags:['Gateau']
    },
    {
        id:'17',
        name:'Sablé',
        cooktime:'15-20',
        price:2,
        favorite:true,
        origins:['italy'],
        stars:4.8,
        imgUrl:'sablé.png',
        tags:['Gateau']
    },
    {
        id:'18',
        name:'Roulé',
        cooktime:'15-20',
        price:2,
        favorite:true,
        origins:['italy'],
        stars:4.8,
        imgUrl:'roulé.png',
        tags:['Gateau']
    },
    {
        id:'19',
        name:'Brawniz',
        cooktime:'15-20',
        price:2,
        favorite:true,
        origins:['italy'],
        stars:4.8,
        imgUrl:'brawniz.png',
        tags:['Gateau']
    },
  

]
export const sampletags =[
    {name : 'All' ,count :19},
    {name : 'FastFood' ,count :11},
    {name : 'Pizza' ,count :1},
    {name : 'Lunch' ,count :5},
    {name : 'SlowFood' ,count :1},
    {name : 'Gateau' ,count :6},
    {name : 'Supplement' ,count :6},
]

